# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  flutter: circleci/flutter@2.1.0
  android: circleci/android@3.1.0

executors:
  android-executor:
    docker:
      - image: circleci/flutter:3.29.2  # Atualize para a vers√£o correta
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

jobs:
  deploy_android:
    executor: android-executor
    type: build

    steps:
      - checkout

      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            java -version

      - flutter/install_sdk_and_pub:
          version: 3.29.2

      - run:
          name: Flutter doctor
          command: flutter doctor -v

      - run:
          name: Build Android using Flutter
          command: flutter build apk --release


workflows:
  version: 2
  deploy:
    jobs:
      - deploy_homolog_android